env:
    global:
        - CC_TEST_REPORTER_ID=4d22ec3bc419bcdfe8bbae9511735bcdf4350af7c0957c6131b72fb23b5305a8
language: node_js
node_js:
    - 8
cache:
    directories:
        - node_modules
before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
script:
    - npm run build
    - npm test
after_script:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
branches:
    only:
        - develop
        - master
        - /^greenkeeper/.*$/
